import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import classNames from 'classnames';

const montserrat = Montserrat({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(montserrat.className, 'text-black', 'text-base')}
      >
        {children}
      </body>
    </html>
  );
}
